apiVersion: v1
kind: Service
metadata:
  name: node-js-service
spec:
  type: NodePort
  selector:
    app: node-js-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080  d